controllers/JourneyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MultipleForm;
use app\models\Spg;
use app\models\SpgJourney;
use app\models\Kecamatan;
use app\models\Team;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\MyFormatter;
use app\models\Kabupaten;
use app\models\SpgSurvey;
use app\models\SpgVenue;
use Exception;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/**
 * JourneyController implements the CRUD actions for SpgJourney model.
 */
class JourneyController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'ruleConfig' => [
                //     'class' => AccessRule::className(),
                // ],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'getdata', 'view', 'delete', 'getkecamatan', 'getteam'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * Lists all SpgJourney models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => SpgJourney::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGetdata()
    {
        $role = Yii::$app->user->identity->role->role;
        $team_id = Yii::$app->user->identity->team_id;
        if ($role == 'super-admin') {
            $dataProvider = new ActiveDataProvider([
                'query' => SpgJourney::find(),
                'pagination'=>false
            ]);
        } elseif ($role == 'admin-regional') {
            $teams_id = [];
            $locations = explode(',', Yii::$app->user->identity->location);
            // get query teams per location
            $query = Team::find();
            foreach($locations as $loc) {
                $query->orFilterWhere(['like', 'area', $loc]);
            }
            $teams = $query->all();
            foreach($teams as $team) {
                array_push($teams_id, $team->id);
            }
            
            $dataProvider = new ActiveDataProvider([
                'query' => SpgJourney::find()->where(['team_id'=>$teams_id]),
                'pagination'=>false
            ]);
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => SpgJourney::find()->where(['team_id'=>$team_id]),
                'pagination'=>false
            ]);
        }

        $result = [];
        $data = [];
        $i = 1;
        foreach ($dataProvider->getModels() as $value) {
            $command = Yii::$app->db->createCommand('SELECT sum(jumlah_beli) FROM spg_survey WHERE `journey_id` = '.$value['id'].' '); // please use a prepared statement instead, just a proof of concept
            $stock_akhir = $command->queryScalar();
            $stock = $value['stock'] - $stock_akhir;

            $nestedData = [];
            $nestedData[] = $i;
            $nestedData[] = $value->spg['nama_spg'];
            $nestedData[] = $value['week'];
            $nestedData[] = $value['kecamatan'];
            $nestedData[] = MyFormatter::formatBlnThn($value['journey_date']);
            $nestedData[] = (int)$stock;
            $nestedData[] = SpgJourney::getActionButton($value['id']);

            $data[] = $nestedData;
            $i++;
        }

        $result = array(
            "data" => $data,
        );

        // echo json_encode($result);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $result;
    }

    public function actionGetkecamatan()
    {
        $team_id = $_GET['team'];
        $query = Kecamatan::find();
        if($team_id != "") {
            $team = Team::find()->where(['id'=>$team_id])->one();
            $kab = Kabupaten::find()->where(['name'=>$team['area']])->one();
            $query = Kecamatan::find()->where(['kabupaten_id'=>$kab['id']]);
        }
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination'=>false
        ]);

        $result = [];
        $data = [];
        foreach ($dataProvider->getModels() as $value) {
            $data[] = $value;
        }

        $result = array(
            "data" => $data,
        );

        // echo json_encode($result);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $result;
    }

    public function actionGetteam()
    {
        // $spg_id = $_GET['spg'];
        // $spg = Spg::find()->where(['id'=>$spg_id])->one();
        // $team = $spg->team->nama_team;
        // $area = $spg->team->area;
        $team_id = $_GET['team_id'];
        $team = Team::find()->where(['id'=>$team_id])->one();
        $area = $team->area;
        $kab = Kabupaten::find()->where(['name'=>$area])->one();
        $data_kecamatan = Kecamatan::find()->where(['kabupaten_id'=>$kab['id']])->orderBy(['name'=>SORT_ASC])->all();
        $data_spg = Spg::find()->where(['team_id'=>$team_id])->orderBy(['nama_spg'=>SORT_ASC])->all();

        $result = array(
            "team" => $team,
            "area" => $area,
            "data_kecamatan" => $data_kecamatan,
            "data_spg" => $data_spg,
        );

        // echo json_encode($result);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $result;
    }

    /**
     * Displays a single SpgJourney model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SpgJourney model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelSpg = new Spg;
        $modelsSpgJourney = [new SpgJourney];
        $modelsSpgVenue = [[new SpgVenue]];
        if (isset($_POST['Spg'])) {
            // die(var_dump($_POST));
            // $spg_id = $_POST['Spg']['id'];
            $list_kecamatan = [];
            $team_id = $_POST['Spg']['id_team'];
            $id_spgs = $_POST['Spg']['id_spgs'];
            $data_spg_per_team = Spg::find()->where(['IN', 'id', $id_spgs])->all();

            $modelsSpgJourney = MultipleForm::createMultiple(SpgJourney::classname());
            MultipleForm::loadMultiple($modelsSpgJourney, Yii::$app->request->post());

            // validate all models
            $valid = MultipleForm::validateMultiple($modelsSpgJourney);

            if (isset($_POST['SpgVenue'][0][0])) {
                foreach ($_POST['SpgVenue'] as $indexJourney => $venues) {
                    foreach ($venues as $indexVenue => $venue) {
                        array_push($list_kecamatan, $venue['kecamatan']);
                        $data['SpgVenue'] = $venue;
                        $modelVenue = new SpgVenue;
                        $modelVenue->load($data);
                        $modelsSpgVenue[$indexJourney][$indexVenue] = $modelVenue;
                        // $valid = $modelVenue->validate();
                    }
                }
            }
            // die(var_dump($modelsSpgVenue[0][0]));

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    $flag = false;
                    foreach ($modelsSpgJourney as $i => $modelSpgJourney) {
                        foreach ($data_spg_per_team as $team) {
                            $journey = new SpgJourney();
                            $journey->spg_id = $team->id;
                            $journey->team_id = $team_id;
                            $journey->week = $_POST['SpgJourney'][$i]['week'];
                            $journey->journey_date = $_POST['SpgJourney'][$i]['journey_date'];
                            $journey->kecamatan = implode(",", array_unique($list_kecamatan)); //implode(",", $_POST['SpgJourney'][$i]['kecamatan']);
                            $journey->stock = $_POST['SpgJourney'][$i]['stock'];
                            $journey->created_at = date('Y-m-d H:i:s');

                            // if (!($flag = $journey->save(false))) {
                            //     break;
                            // }
                            if ($journey->save(false)) {
                                if (isset($modelsSpgVenue[$i]) && is_array($modelsSpgVenue[$i])) {
                                    foreach ($modelsSpgVenue[$i] as $indexVenue => $modelVenue) {
                                        $venue = new SpgVenue();
                                        $venue->kecamatan = $modelVenue->kecamatan;
                                        $venue->venue = $modelVenue->venue;
                                        $venue->journey_id = $journey->id;
                                        $venue->created_at = date('Y-m-d H:i:s');
                                        if (!($flag = $venue->save(false))) {
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }

                    if ($flag) {
                        $transaction->commit();

views/journey/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;
use app\models\Kecamatan;
use app\models\Spg;
use app\models\Team;

/* @var $this yii\web\View */
/* @var $model app\models\SpgJourney */
/* @var $form yii\widgets\ActiveForm */
?>

<!-- <style>
.datepicker {
    width: 100% !important;
}
</style> -->

<div class="spg-journey-form">
    <?php $form = ActiveForm::begin([
        'id' => 'dynamic-form',
        'options' => [
            'class' => 'm-form m-form--fit m-form--label-align-right'
        ]
    ]); ?>

    <div class="row">
        <div class="col-sm-6">
        <?php if($modelSpg->isNewRecord) { ?>
            <?= $form->field($modelSpg, 'id_team')->dropDownList(Team::getDataTeam(), ['prompt'=>'-- Pilih Tim --', 'class'=>'form-control m-input m-input--square', 'required'=>'required', 'onchange'=>'getTeam(this.value, "new")']) ?>
        <?php } else { ?>
            <?= $form->field($modelSpg, 'team_id')->dropDownList(Team::getDataTeam(), ['prompt'=>'-- Pilih Tim --', 'class'=>'form-control m-input m-input--square', 'required'=>'required', 'disabled'=>'disabled']) ?>
        <?php } ?>
        </div>
        <?php if($modelSpg->isNewRecord) { ?>
        <div class="col-sm-6">
        <?= $form->field($modelSpg, 'id_spgs')->dropDownList([], ['prompt'=>'Pilih Tim Dahulu', 'class'=>'form-control m-input m-input--square select2', 'required'=>'required', 'multiple'=>'multiple']) ?>
        </div>
        <?php } ?>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h4><i class="m-menu__link-icon fa fa-map-marker-alt"></i> Journey SPG</h4></div>
        <div class="panel-body">
             <?php DynamicFormWidget::begin([
                'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                'widgetBody' => '.container-items', // required: css class selector
                'widgetItem' => '.item', // required: css class
                'limit' => 7, // the maximum times, an element can be cloned (default 999)
                'min' => 1, // 0 or 1 (default 1)
                'insertButton' => '.add-item', // css class
                'deleteButton' => '.remove-item', // css class
                'model' => $modelsSpgJourney[0],
                'formId' => 'dynamic-form',
                'formFields' => [
                    'week',
                    'journey_date',
                    'kecamatan',
                    'stock',
                ],
            ]); ?>

            <div class="container-items">
            <?php foreach ($modelsSpgJourney as $indexJourney => $modelSpgJourney): ?>
                <?= $form->errorSummary($modelSpgJourney); ?>
                <div class="item panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title-idx"></h3>
                        <?php if($modelSpgJourney->isNewRecord) : ?>
                        <div class="pull-right">
                            <button type="button" class="add-item btn btn-success m-btn m-btn--icon m-btn--icon-only"><i class="glyphicon glyphicon-plus"></i></button>
                            <button type="button" class="remove-item btn btn-danger m-btn m-btn--icon m-btn--icon-only"><i class="glyphicon glyphicon-minus"></i></button>
                        </div>
                        <?php endif; ?>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <?php
                            // necessary for update action
                            if (!$modelSpgJourney->isNewRecord) {
                                echo Html::activeHiddenInput($modelSpgJourney, "[{$indexJourney}]id");
                            }
                        ?>
                        <div class="row">
                            <div class="col-sm-6">
                                <?= $form->field($modelSpgJourney, "[{$indexJourney}]week")->textInput(['maxlength' => true, 'type' => 'number']) ?>
                            </div>
                            <div class="col-sm-6">
                                <?= $form->field($modelSpgJourney, "[{$indexJourney}]journey_date")->textInput(['maxlength' => true, 'class' => 'form-control datepicker']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <?= $form->field($modelSpgJourney, "[{$indexJourney}]stock")->textInput(['maxlength' => true, 'type' => 'number']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <?= $modelSpg->isNewRecord ? $this->render('_form_venue', [
                                    'form' => $form,
                                    'indexJourney' => $indexJourney,
                                    'modelSpg' => $modelSpg,
                                    'modelsSpgVenue' => $modelsSpgVenue[$indexJourney],
                                ]) : $this->render('_form_venue', [
                                    'form' => $form,
                                    'indexJourney' => $indexJourney,
                                    'modelSpg' => $modelSpg,
                                    'modelsSpgVenue' => $modelsSpgVenue[$indexJourney],
                                    'kabupaten' => $kabupaten,
                                ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
            <?php DynamicFormWidget::end(); ?>
        </div>
    </div>

    <div class="m-form__actions m-form__actions">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <?= Html::submitButton('<i class="fa fa-check"></i> Save', ['class' => 'btn btn-success']) ?>
                <button type="button" class="btn btn-secondary" onclick="goBack()"><i class="fa fa-times"></i> Cancel</button>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<?php
$js = <<<'EOD'

jQuery(".dynamicform_wrapper").on("afterInsert", function(e, item) {
    $("#"+$(item).find('.select2')[0].id).empty();
    $("#"+$(item).find('.select2')[0].id).select2({data: model.data()});
    
    jQuery(".dynamicform_wrapper").each(function(index) {
        $(".datepicker").datepicker({
            format: "yyyy-mm-dd",
            todayHighlight: true,
            autoclose: true,
        });
    });
});

jQuery(".dynamicform_inner").on("afterInsert", function(e, item) {
    $("#"+$(item).find('.select2')[0].id).empty();
    $("#"+$(item).find('.select2')[0].id).select2({data: model.data()});
});

EOD;

$this->registerJs($js);
?>

<script>
    var url = '<?= Url::to(['/journey/getteam']); ?>';
    var model = {};
    model.data = ko.observableArray([]);
    model.dataSpg = ko.observableArray([]);
    function getTeam(id, isUpdate=null) {        
        $.ajax({
            url: url,
            type: "GET",
            cache: false,
            data: { "team_id": id },
            success: function (res) {
                $("#team-spg").val(res.team + ' - ' + res.area);
                var data = $.map(res.data_kecamatan, function(obj) {
                    return { id: obj.name, text: obj.name };
                });
                var dataSpg = $.map(res.data_spg, function(obj) {
                    return { id: obj.id, text: obj.nama_spg };
                });
                model.data(data);
                model.dataSpg(dataSpg);
                // console.log("dt :: ", data);
                if (isUpdate) {
                    $(".select2").empty();
                    $(".select2").select2({data: data});

                    $("#spg-id_spgs").empty();
                    $("#spg-id_spgs").select2({data: dataSpg});
                }
            },
            error: function (data) {
                console.log(data);
            }
        });
    }
    
    $(document).ready(function () {
        var elementExists = document.getElementById("spg-team_id");
        if (elementExists) {
            getTeam($('#spg-team_id').val());
        }
    });
</script>

views/journey/_form_kecamatan.php
<?php

use yii\helpers\Html;
use wbraganca\dynamicform\DynamicFormWidget;

?>
<?php DynamicFormWidget::begin([
    'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
    'widgetBody' => '.container-items', // required: css class selector
    'widgetItem' => '.item', // required: css class
    'limit' => 7, // the maximum times, an element can be cloned (default 999)
    'min' => 1, // 0 or 1 (default 1)
    'insertButton' => '.add-item', // css class
    'deleteButton' => '.remove-item', // css class
    'model' => $modelsSpgJourney[0],
    'formId' => 'dynamic-form',
    'formFields' => [
        'week',
        'journey_date',
        'kecamatan',
        'stock',
    ],
]); ?>

    <table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Kecamatan</th>
            <th style="width: 450px;">Venue</th>
            <th class="text-center" style="width: 90px;">
                <button type="button" class="add-item btn btn-success btn-xs"><span class="fa fa-plus"></span></button>
            </th>
        </tr>
    </thead>
    <tbody class="container-items">
        <?php foreach ($modelsSpgJourney as $indexJourney => $modelJourney): ?>
            <tr class="item">
                <td class="vcenter">
                    <?php
                        // necessary for update action.
                        if (! $modelJourney->isNewRecord) {
                            echo Html::activeHiddenInput($modelJourney, "[{$indexJourney}]id");
                        }
                    ?>
                    <?= $form->field($modelJourney, "[{$indexJourney}]week")->label(false)->textInput(['maxlength' => true]) ?>
                </td>
                <td>
                    <?= $this->render('_form_venue', [
                        'form' => $form,
                        'indexJourney' => $indexJourney,
                        'modelsSpgVenue' => $modelsSpgVenue[$indexJourney],
                    ]) ?>
                </td>
                <td class="text-center vcenter" style="width: 90px; verti">
                    <button type="button" class="remove-house btn btn-danger btn-xs"><span class="fa fa-minus"></span></button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

<?php DynamicFormWidget::end(); ?>

views/journey/_form_venue.php
<?php

use yii\helpers\Html;
use wbraganca\dynamicform\DynamicFormWidget;
use app\models\Kecamatan;

?>

<?php DynamicFormWidget::begin([
    'widgetContainer' => 'dynamicform_inner',
    'widgetBody' => '.container-venues',
    'widgetItem' => '.venue-item',
    // 'limit' => 4,
    'min' => 1,
    'insertButton' => '.add-venue',
    'deleteButton' => '.remove-venue',
    'model' => $modelsSpgVenue[0],
    'formId' => 'dynamic-form',
    'formFields' => [
        'kecamatan',
        'venue'
    ],
]); ?>

<table class="table table-bordered">
    <thead>
        <tr>
            <th class="text-center" style="vertical-align: middle; width: 30%;">Kecamatan</th>
            <th class="text-center" style="vertical-align: middle;">Venue</th>
            <th class="text-center">
                <button type="button" class="add-venue btn btn-success m-btn m-btn--icon m-btn--icon-only"><i class="glyphicon glyphicon-plus"></i></button>
            </th>
        </tr>
    </thead>
    <tbody class="container-venues">
    <?php foreach ($modelsSpgVenue as $indexVenue => $modelVenue): ?>
        <?= $form->errorSummary($modelVenue); ?>
        <?php
            // die(var_dump($indexVenue));
            // if (!$modelVenue->isNewRecord) {
            //     echo Html::activeHiddenInput($modelVenue, "[{$indexJourney}][{$indexVenue}]id");
            // }
        ?>
        <tr class="venue-item">
            <td class="vcenter">
                <?php if ($modelSpg->isNewRecord) { ?>
                <?= $form->field($modelVenue, "[{$indexJourney}][{$indexVenue}]kecamatan")->label(false)->dropDownList(Kecamatan::getDataKecamatan(3516), ['class'=>'form-control select2']) ?>
                <?php } else { ?>
                    <?= $form->field($modelVenue, "[{$indexJourney}][{$indexVenue}]kecamatan")->label(false)->dropDownList(Kecamatan::getDataKecamatan($kabupaten->id), ['class'=>'form-control select2']) ?>
                <?php } ?>
            </td>
            <td class="vcenter">
                <?= $form->field($modelVenue, "[{$indexJourney}][{$indexVenue}]venue")->label(false)->textInput(['maxlength' => true, 'class' => 'form-control']) ?>
            </td>
            <td class="text-center vcenter" style="width: 90px;">
                <button type="button" class="remove-venue btn btn-danger m-btn m-btn--icon m-btn--icon-only"><i class="glyphicon glyphicon-minus"></i></button>
            </td>
        </tr>
     <?php endforeach; ?>
    </tbody>
</table>
<?php DynamicFormWidget::end(); ?>

views/journey/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SpgJourneySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="spg-journey-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'spg_id') ?>

    <?= $form->field($model, 'week') ?>

    <?= $form->field($model, 'journey_date') ?>

    <?= $form->field($model, 'journey_day') ?>

    <?php // echo $form->field($model, 'kecamatan') ?>

    <?php // echo $form->field($model, 'stock') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/journey/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\SpgJourney */

$this->title = 'Create SPG Journey';
$this->params['breadcrumbs'][] = ['label' => 'Data SPG Journey', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="spg-journey-create">
    <div class="m-portlet m-portlet--tab">  
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon">
                        <i class="fa fa-users"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        <?= $this->title; ?>
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <?= $this->render('_form', [
                'modelSpg' => $modelSpg,
                'modelsSpgJourney' => $modelsSpgJourney,
                'modelsSpgVenue' => $modelsSpgVenue,
            ]) ?>
        </div>
    </div>
</div>

views/journey/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data Journey SPG';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="spg-journey-index">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?= $this->title; ?>
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                        <?= Html::a('<span><i class="fa fa-plus"></i><span>Tambah Data</span></span>', ['create'], ['class' => 'btn btn-success m-btn m-btn--custom m-btn--icon m-btn--air']) ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="m-portlet__body">
        <?= Yii::$app->session->getFlash('info'); ?>
            <!--begin: Datatable -->
            <table id="tablegrid" class="table table-striped- table-bordered table-hover table-checkable" width="100%">
                <thead>
                    <tr>
                        <th width="10px">No</th>
                        <th width="90px">Nama SPG</th>
                        <th width="40px">Week</th>
                        <th width="40px">Kecamatan</th>
                        <th width="40px">Date</th>
                        <th width="40px">Stock</th>
                        <th width="40px">#</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

views/journey/update.php
<?php

use app\models\Kabupaten;
use app\models\Kecamatan;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SpgJourney */

$this->title = 'Update Spg Journey: ' . $modelSpg->nama_spg;
$this->params['breadcrumbs'][] = ['label' => 'Data Journey SPG', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="spg-journey-update">
    <div class="m-portlet m-portlet--tab">  
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon">
                        <i class="fa fa-users"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        <?= $this->title; ?>
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <?= $modelSpg->isNewRecord ? $this->render('_form', [
                'modelSpg' => $modelSpg,
                'modelsSpgJourney' => $modelsSpgJourney,
                'modelsSpgVenue' => $modelsSpgVenue,
            ]) : $this->render('_form', [
                'modelSpg' => $modelSpg,
                'modelsSpgJourney' => $modelsSpgJourney,
                'modelsSpgVenue' => $modelsSpgVenue,
                'kabupaten' => $kabupaten,
            ]) ?>
        </div>
    </div>
</div>

views/journey/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\SpgJourney */

$this->title = $model->spg->nama_spg;
$this->params['breadcrumbs'][] = ['label' => 'Data Journey SPG', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="spg-journey-view">
    <div class="m-portlet m-portlet--mobile">   
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <?= $this->title; ?>
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                        <?= Html::a('<span><i class="fa fa-pencil-alt"></i><span>Edit Data</span></span>', ['update', 'id' => $model->id], ['class' => 'btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air']) ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="m-portlet__body">
            <?= Yii::$app->session->getFlash('info'); ?>
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'week',
                    'journey_date',
                    'kecamatan',
                    'stock',
                ],
            ]) ?>
        </div>
    </div>
</div>